scientific-python/cookie

{{cookiecutter.project_name}}/.github/workflows/ci.yml
{{cookiecutter.project_name}}/.github/workflows/wheels-pybind11.yml

https://github.com/pipxproject/pipx/pull/615 is now available in the latest GitHub Actions runners, so we can drop the old `--spec` portion.

chore: use newer pipx run syntax

---

{{cookiecutter.project_name}}/docs/conf.py
{{cookiecutter.project_name}}/pyproject-flit.toml
{{cookiecutter.project_name}}/pyproject-poetry.toml
{{cookiecutter.project_name}}/setup.cfg

Cleaning up the default, and switching to myst-parser. CC https://github.com/readthedocs/recommonmark/issues/221

docs: convert recommonmark to myst-parser

---

{{cookiecutter.project_name}}/.flake8
{{cookiecutter.project_name}}/.github/workflows/ci-pybind11.yml
{{cookiecutter.project_name}}/.github/workflows/ci.yml
{{cookiecutter.project_name}}/.github/workflows/wheels-pybind11.yml
{{cookiecutter.project_name}}/.pre-commit-config.yaml
{{cookiecutter.project_name}}/pyproject-flit.toml
{{cookiecutter.project_name}}/pyproject-poetry.toml
{{cookiecutter.project_name}}/pyproject-pybind11.toml
{{cookiecutter.project_name}}/pyproject-setuptools.toml
{{cookiecutter.project_name}}/setup-setuptools,pybind11.cfg
{{cookiecutter.project_name}}/setup-setuptools.py

Using pyproject.toml more heavily, now that mypy supports it.
I might remove setup.py from the regular setuptools version, as it's no longer needed, and encourages bad practice, like `python setup.py <X>`.

feat: use pyproject.toml more heavily

---

.github/workflows/ci.yml
README.md
cookiecutter.json
hooks/post_gen_project.py
noxfile.py
{{cookiecutter.project_name}}/.github/workflows/ci-trampolim.yml
{{cookiecutter.project_name}}/.pre-commit-config.yaml
{{cookiecutter.project_name}}/pyproject-flit621,trampolim.toml

Added PEP 621 support for Flit and added trampolim.
* Flit SDists have bad dist-info files that produces twine warnings, but that's not new.
* Trampolim products don't pass twine due to twine not supporting metadata 2.2 - skipping check
* Needed a duplicate CI file due to upload action checking by default - also added "pre"-check for non-release runs.
* Trampolim doesn't support `/src` structure (or editable installs) yet (at least src should come soon, thanks to @FFY00), so that one does not make `/src` structure for now. https://github.com/FFY00/trampolim/issues/3
* Trampolin is Python 3.7+, but wheels should support 3.6+, I'd think.

feat: add PEP 621 support (flit and trampolim)

---

noxfile.py
{{cookiecutter.project_name}}/pyproject-flit621,trampolim.toml

Followup to #21, making the version dynamic (flit reads it from the file, trampolim gets it from VCS).

feat: dynamic versions for trampolim/flit621

---

noxfile.py
{{cookiecutter.project_name}}/.pre-commit-config.yaml

This prints out what needs to be updated when run (by hand) with `nox -s autoupdate`.

feat: easier nox-powered update procedure for pre-commit

---

.github/workflows/ci.yml
{{cookiecutter.project_name}}/.github/workflows/ci-pybind11.yml
{{cookiecutter.project_name}}/.github/workflows/ci-trampolim.yml
{{cookiecutter.project_name}}/.github/workflows/ci.yml
{{cookiecutter.project_name}}/.github/workflows/wheels-pybind11.yml
{{cookiecutter.project_name}}/.pre-commit-config.yaml
{{cookiecutter.project_name}}/pyproject-flit.toml
{{cookiecutter.project_name}}/pyproject-flit621,trampolim,whey.toml
{{cookiecutter.project_name}}/pyproject-poetry.toml
{{cookiecutter.project_name}}/setup-setuptools,pybind11.cfg

Dropping numpy, as they are really slow getting out wheels sometimes. 3.10 Windows and macOS, for example. And musllinux.

feat: support Python 3.10

---

{{cookiecutter.project_name}}/pyproject-pybind11.toml
{{cookiecutter.project_name}}/pyproject-setuptools.toml

Counterpart to https://github.com/scikit-hep/scikit-hep.github.io/pull/177

fix: setuptools declares wheel/sdist dependencies already

---

{{cookiecutter.project_name}}/pyproject^setuptools,pybind11,poetry.toml

Hi @henryiii, we previously discussed that it would be nice to have automatic discovery for the src-layout, and that was my original intention when implementing project metadata support (this way users have to write as little custom configuration as possible).
This PR is just an experiment to see how it would work on this project (on top of your previous experimental PR).
Currently [auto-discory](https://setuptools--2894.org.readthedocs.build/en/2894/userguide/package_discovery.html#automatic-discovery) works best with the src-layout. It will also work on flat-layout, however if the package has too many custom folders things might ended up added in the wheel.

[EXPERIMENT] Use setuptools auto-discovery for `src-layout`

---

{{cookiecutter.project_name}}/.pre-commit-config.yaml

Motivated by https://github.com/scikit-hep/scikit-hep.github.io/issues/227 and complimentary to PR https://github.com/scikit-hep/scikit-hep.github.io/pull/231.
* Update pre-commit/pre-commit-hooks to v4.3.0
* Add the 'name-tests-test' pre-commit hooks which verifies that test files under `tests/` conform to `pytest` naming conventions.
- Use the `--pytest-test-first` option to match the `test_.*\.py` naming convention.

feat: Add 'name-tests-test' to pre-commit hooks

---

.github/workflows/ci.yml
{{cookiecutter.project_name}}/.github/workflows/ci-pybind11.yml
{{cookiecutter.project_name}}/.github/workflows/ci-trampolim.yml
{{cookiecutter.project_name}}/.github/workflows/ci.yml
{{cookiecutter.project_name}}/.github/workflows/wheels-pybind11.yml
{{cookiecutter.project_name}}/.pre-commit-config.yaml

Includes the setup-python v4 update, seehttps://github.com/actions/setup-python/issues/421.
- chore: bump GHA versions
- chore: bump pre-commit versions

chore: update versions

---

.github/dependabot.yml

No longer needed (April 2022+).

fix: update dependabot ignore

---

{{cookiecutter.project_name}}/setup-skbuild.py

Closes #98. For a first try, I'm thinking we don't actually need to include any package data, since CMakeLists.txt and stuff doesn't go in the wheel. But maybe I'm forgetting something.

fix: remove include_package_data

---

{{cookiecutter.project_name}}/.pre-commit-config.yaml

Flake8 now requires Python 3.8+, hopefully won't break CI.

chore: update pre-commit hooks

---

.github/workflows/ci.yml

Fixes the "pass on fail" feature of the previous implementation. This was not exposed in the cookiecutter, just in our own tests. Thanks to @webknjaz in https://github.com/pypa/build/pull/543 and https://github.com/mesonbuild/meson-python/pull/221#discussion_r1038060140.

ci: fix pass job

---

{{cookiecutter.project_name}}/.pre-commit-config.yaml
{{cookiecutter.project_name}}/CMakeLists-skbuild.txt

See https://github.com/PyCQA/isort/pull/2078. Also GitHub [broke all hashes](https://github.blog/changelog/2023-01-30-git-archive-checksums-may-change/) for a few minutes, but it's back to normal. Might as well keep the pybind11 bump, though.

fix: poetry-core 1.5.0 broke isort

---

{{cookiecutter.project_name}}/pyproject.toml

The logic for lib names and sources changed, 0.15 broke us with https://github.com/PyO3/maturin/pull/1335 and https://github.com/PyO3/maturin/pull/1608 looks suspect too.

fix: limit maturin

---

docs/pages/developers/gha_basic.md
docs/pages/developers/gha_wheels.md
docs/pages/developers/index.md
docs/pages/developers/intro.md
docs/pages/developers/nox.md
docs/pages/developers/packaging.md
docs/pages/developers/pep621.md
docs/pages/developers/style.md

Updating language to be less organization specific and apply to the general scientific Python community.
There are still a handful of remaining "hep" references:
- in `repo_review.md`
- in some code such as
```HTML
<div class="skhep-bar d-flex m-2" style="justify-content:center;">
<button class="skhep-bar-item oidc-btn btn  m-2 btn-purple" onclick="openTab('oidc')">Trusted Publishing</button>
<button class="skhep-bar-item token-btn btn m-2" onclick="openTab('token')">Token</button>
</div>
<div class="skhep-tab oidc-tab" markdown="1">
```

Replace specific references to Scikit-HEP

---

.github/workflows/ci.yml

This uses [an approach borrowed from matplotlib](https://github.com/matplotlib/matplotlib/blob/main/.github/workflows/tests.yml).
In the future this could be revisited to use a [more sophisticated approach](https://github.com/pypa/build/blob/main/.github/workflows/reusable-change-detection.yml)
which marks the overall build as "passing" even though the non-applicable jobs were skipped.

Skip build when the only changes were under docs/

---

.gitignore
.readthedocs.yml
docs/_config.yml
docs/pages/guides/coverage.md
docs/pages/guides/gha_basic.md
docs/pages/guides/gha_pure.md
docs/pages/guides/gha_wheels.md
docs/pages/guides/index.md
docs/pages/guides/mypy.md
docs/pages/guides/nox.md
docs/pages/guides/packaging.md
docs/pages/guides/pep621.md
docs/pages/guides/pytest.md
docs/pages/guides/repo_review.md
docs/pages/guides/style.md
docs/pages/patterns/index.md
docs/pages/principles/index.md
docs/pages/tutorials/dev-environment.md
docs/pages/tutorials/index.md

Working on this. Example env:
```
READTHEDOCS_VIRTUALENV_PATH=/home/docs/checkouts/readthedocs.org/user_builds/scikit-hep-cookie/envs/142
READTHEDOCS_CANONICAL_URL=https://scikit-hep-cookie--142.org.readthedocs.build/en/142/
HOSTNAME=build-20808251-project-1003427-scikit-hep-cookie
READTHEDOCS_GIT_CLONE_URL=https://github.com/scikit-hep/cookie.git
HOME=/home/docs
NO_COLOR=1
READTHEDOCS=True
READTHEDOCS_PROJECT=scikit-hep-cookie
READTHEDOCS_OUTPUT=/home/docs/checkouts/readthedocs.org/user_builds/scikit-hep-cookie/checkouts/142/_readthedocs/
PATH=/home/docs/checkouts/readthedocs.org/user_builds/scikit-hep-cookie/envs/142/bin:/home/docs/.asdf/shims:/home/docs/.asdf/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
READTHEDOCS_VERSION_TYPE=external
LANG=C.UTF-8 …
```

ci: fix readthedocs linking and css

---

docs/pages/guides/repo_review.md

Use dashes everywhere.
Closes #147
Unless maybe we want a CI action that check that "reporeview" is not present in the source/filenames of this repo.

Repo-review consistency.

---

docs/pages/guides/gha_basic.md
docs/pages/guides/gha_pure.md
docs/pages/guides/gha_wheels.md
docs/pages/guides/mypy.md
docs/pages/guides/packaging_classic.md
docs/pages/guides/packaging_simple.md
docs/pages/guides/style.md
docs/pages/guides/writing-docs.md

This is adapted from https://nsls-ii.github.io/scientific-python-cookiecutter/writing-docs.html.
We have intentionally omitted the sections on the IPython and Maplotlib (`.. plot:`) sphinx directives. Extension that execute code would probably be better addressed in a separate section, and we want to take some extra time to get familiar with current best practice. Best practice here seems to have evolved; it may be better to recommend Jupytext.

Add guide on writing docs

---

.devcontainer/devcontainer.json

Adding a container config from the open spec (containers.dev) that will help contributors in VS Code, Codespaces + Jetbrains tools have similar development experiences. It uses a basic Python Docker container, adds a Rust feature, and then installs nox and maturin. I have tested and all of the nox sessions pass.

Dev Container config

---

docs/_includes/head_custom.html
docs/assets/js/webapp.js

Probably the last update before the split & move.

chore: bump repo review to 0.6.1

---

.github/workflows/reusable-cookie.yml
cookiecutter.json
hooks/post_gen_project.py
noxfile.py
{{cookiecutter.project_name}}/.github/CONTRIBUTING.md
{{cookiecutter.project_name}}/.github/workflows/ci.yml
{{cookiecutter.project_name}}/.pre-commit-config.yaml
{{cookiecutter.project_name}}/noxfile.py
{{cookiecutter.project_name}}/pyproject.toml
{{cookiecutter.project_name}}/src/{{cookiecutter.__project_slug}}/__init__.py

This is how the README already refers to it, and it's fewer characters for the thing that's coming next.
- ci: use pre-releases for 3.12 instead of dev
- refactor: use backend instead of project_type

refactor: use backend instead of project_type

---

.github/workflows/reusable-cookie.yml
README.md
docs/pages/guides/gha_basic.md
docs/pages/guides/mypy.md
docs/pages/guides/packaging_classic.md
docs/pages/guides/packaging_simple.md
docs/pages/guides/pytest.md
docs/pages/guides/style.md
docs/pages/guides/tasks.md
{{cookiecutter.project_name}}/.github/workflows/ci.yml
{{cookiecutter.project_name}}/.pre-commit-config.yaml
{{cookiecutter.project_name}}/pyproject.toml
{{cookiecutter.project_name}}/src/{{cookiecutter.__project_slug}}/_compat/typing.py
{{cookiecutter.project_name}}/tests/test_package.py
{{cookiecutter.project_name}}/{% if cookiecutter.backend in ['setuptools','pybind11'] %}setup.cfg{% endif %}
{{cookiecutter.project_name}}/{% if cookiecutter.backend=='maturin' %}Cargo.toml{% endif %}

~~Tomorrow~~ Today 3.7 is EoL.
I've added some <3.11 examples to the typing backports, since we don't have <3.8 ones anymore. We could fill it out in the future.

chore: drop Python 3.7

---

src/sp_repo_review/checks/__init__.py

Now that the badges are released, we can link to them.

chore: use released version of pages in sp-repo-review

---

{{cookiecutter.project_name}}/{% if cookiecutter.license == 'Apache' %}LICENSE{% endif %}
{{cookiecutter.project_name}}/{% if cookiecutter.license == 'BSD' %}LICENSE{% endif %}
{{cookiecutter.project_name}}/{% if cookiecutter.license == 'MIT' %}LICENSE{% endif %}

Now that we are using templated filenames, this is more natural.

chore: rework license file template

---

{{cookiecutter.project_name}}/README.md
{{cookiecutter.project_name}}/pyproject.toml
{{cookiecutter.project_name}}/{% if cookiecutter.backend in ['setuptools','pybind11'] %}setup.cfg{% endif %}

This fixes #112 by removing the gitter badge - it's hard to compute the URL correctly, and projects might not use Gitter. Also makes the org integration a bit nicer, as exact capitalization no longer needs to be followed.

fix: badge links

---

_config.yml
docs/pages/guides/coverage.md
docs/pages/guides/docs.md
docs/pages/guides/gha_pure.md
docs/pages/guides/packaging_classic.md
docs/pages/guides/packaging_simple.md
docs/pages/guides/pytest.md
docs/pages/guides/tasks.md
docs/pages/principles/design.md
docs/pages/tutorials/dev-environment.md
docs/pages/tutorials/module.md

There's now nice formatting tools in justthedocs for callouts (0.4+).
Also adding the missing Commmand line section.

fix: formatting of callouts

---

README.md
noxfile.py

See https://github.com/copier-org/copier/issues/1225.

fix: copier and pydantic 2 are not compatible

---

.pre-commit-config.yaml
src/sp_repo_review/checks/precommit.py

Ruff has moved to a proper organization a couple weeks back. While GitHub automatically redirects, it's probably best to update the corresponding check.

chore: update ruff repo link

---

docs/pages/guides/style.md
pyproject.toml
src/sp_repo_review/checks/ruff.py
{{cookiecutter.project_name}}/pyproject.toml

Closes #201.
I hope I covered all places that need to be changed. Not too familiar with all of the code base yet.

feat: infer ruff target version

---

cookiecutter.json

Cookiecutter 2.2 is incompatible out of the box with cookie. This gets it working again for now, we'll see what happens on https://github.com/cookiecutter/cookiecutter/pull/1779. I'd like to keep support for <2.2 for a while, until it's rare from package managers and such.

fix: cookiecutter 2.2 removed jinja2_time

---

.pre-commit-config.yaml
README.md
cookiecutter.json
copier.yml
helpers/cog_cc.py

If a user is using cookiecutter 2.2 (from about 3-4 hours ago, feature added in https://github.com/cookiecutter/cookiecutter/pull/1881), they will get nice descriptions now! Using cog to keep these in sync with copier.
Copier's choices are still much nicer, but this is a great step in the right direction.
New output when using cookiecutter 2.2+:
```
The name of your project [package]:
The name of your (GitHub?) org [org]:
The url to your GitHub or GitLab repository [https://github.com/org/package]:
Your name [My Name]:
Your email [me@email.com]:
A short description of your project [A great package.]:
Select a license:
1 - BSD
2 - Apache
3 - MIT
Choose from 1, 2, 3 [1]:
Choose a build backend:
1 - hatch
2 - flit
3 - pdm
4 - trampolim
5 - whey
6 - poetry
7 - setuptools621
8 - setuptools
9 - …
```

fix: nice cookie descriptions

---

cookiecutter.json

This is present by default! See https://github.com/cookiecutter/cookiecutter/issues/1888.

fix: restore dynamic time

---

README.md

This README misspelled `pydantic` as `pydandic`. So I think this fixes it, it doesn't seem like there's any other package that's called `pydandic`.

Fix misspelling of Pydantic

---

README.md
cookiecutter.json
copier.yml
docs/pages/guides/packaging_compiled.md
helpers/cog_cc.py
noxfile.py

Cookiecutter 2.2.3 now provides full help text even on the choices. 2.2.0 and 2.2.2 produce a weird repr of a OrderedDict, but still work (and old versions work like before). Synced choices with cog now too.
Updated for latest copier features, including `--safe` and the pydantic bug avoided.
New display:
```
The name of your project [package]:
The name of your (GitHub?) org [org]:
The url to your GitHub or GitLab repository [https://github.com/org/package]:
Your name [My Name]:
Your email [me@email.com]:
A short description of your project [A great package.]:
Select a license:
1 - BSD
2 - Apache
3 - MIT
Choose from 1, 2, 3 [1]:
Choose a build backend:
1 - Hatchling                      - Pure Python (recommended)
2 - Flit-core                      - Pure Python (minimal)
3 - PDM-backend …
```

fix: help text / choice improvements

---

docs/pages/index.md

We renamed/rebranded the project recently:
- https://github.com/scipy-lectures/scientific-python-lectures/pull/574
- https://github.com/scipy-lectures/scientific-python-lectures/issues/587

Update link to lecture notes

---

.pre-commit-config.yaml
docs/pages/guides/coverage.md
docs/pages/guides/docs.md
docs/pages/guides/packaging_compiled.md
docs/pages/guides/tasks.md
helpers/cog_helpers.py
noxfile.py
{{cookiecutter.project_name}}/noxfile.py

Docs nox job more like packaging.python.org's job.
More cogging, with an extra utility. Nox sessions are synced with output via cog too now.

fix: better and more generation, docs job improvement

---

{{cookiecutter.project_name}}/pyproject.toml

Removed from docs, missed in cookiecutter. Not needed anymore.

fix: remove unneeded pytest ignore

---

{{cookiecutter.project_name}}/.github/workflows/ci.yml
{{cookiecutter.project_name}}/.github/workflows/{% if cookiecutter.__type!='compiled' %}cd.yml{% endif %}

Drop extra branches. The default is solidly `main` now, and ppl can update if needed. Simpler template better.

fix: drop extra branches

---

docs/pages/tutorials/packaging.md

Very small change, but the tutorial should say `toml` here instead of `yaml`. This fixes the typo.

Fix erroneous reference to YAML in packaging.md

---

docs/pages/guides/packaging_compiled.md
{{cookiecutter.project_name}}/pyproject.toml
{{cookiecutter.project_name}}/{% if cookiecutter.backend=='maturin' %}Cargo.toml{% endif %}

Quick fix for limit, 1.0 came out. Not fond of the limit at all, really, but following Maturin's docs.

fix: update maturin

---

docs/pages/guides/style.md
{{cookiecutter.project_name}}/noxfile.py
{{cookiecutter.project_name}}/pyproject.toml
{{cookiecutter.project_name}}/{% if cookiecutter.__ci=='gitlab' %}.gitlab-ci.yml{% endif %}

Noticed when helping at TAC-HEP with https://github.com/ckoraka/tac-hep-coding-jam students.

fix: pylint should run on compiled code

---

docs/_includes/interactive_repo_review.html
docs/assets/js/webapp.js
pyproject.toml
src/sp_repo_review/families.py

Updating to 0.9 & adding dynamic description.

feat: use repo-review 0.9 dynamic descriptions

---

pyproject.toml

We have had issues with the upper cap in the past, and now we have having issues with the lower cap, so let's just remove them. See https://github.com/scientific-python/repo-review/issues/123

fix: remove limits on repo-review

---

.pre-commit-hooks.yaml
README.md

When trying to use the pre-commit hook as suggested by https://github.com/scientific-python/repo-review/issues/123#issuecomment-1672479812 I found several issues:
1. The hook would fail to install due to the `.pre-commit-hooks.yaml` file not containing a `list` and instead being a `dict`.
2. `repo-review` would fail to run if it was passed all the individual files, which is the default behavior of `pre-commit`.
3. Several dependencies for `repo-review` to function as a CLI tool for `pre-commit` failed to be installed.
This attempts to solve all these small issues.

Fix the pre-commit hook

---

docs/pages/guides/gha_basic.md

Fixes a small typo in the documentation.

fix: typo in gha_basic

---

docs/pages/guides/docs.md

docs: exectutable update

---

docs/pages/patterns/data_files.md

Thanks for the docs! Here are a few minor tweaks.
Fix a few encoding values from `utf=8` to `utf-8`.
The setuptools data file example was a bit confusing, since the default behaviour of `pyproject.toml` is described, but is followed by an example for `setup.cfg`.
Perhaps in a few years all `setup.cfg` examples should be either removed or replaced with standard-based `pyproject.toml`.

docs: fix encoding; clarify example is for setup.cfg

---

docs/_includes/interactive_repo_review.html

This is supported now. Also adding scikit-build-core for it's validation schema.

fix: add validate-pyproject to checks

---

docs/pages/guides/style.md
{{cookiecutter.project_name}}/.pre-commit-config.yaml

Missed when updating this earlier.

docs: update for rename of blacken-docs

---

docs/_includes/interactive_repo_review.html
src/sp_repo_review/checks/mypy.py
src/sp_repo_review/checks/pyproject.py
src/sp_repo_review/checks/readthedocs.py
src/sp_repo_review/checks/ruff.py

Adding example to many of the other checks, for easier copy/paste fixing.

fix: add more examples to error messages

---

docs/pages/guides/docs.md

I guess it was referring to the Lutra, but it's not ready yet and the 3.13 docs still use https://github.com/python/python-docs-theme, like the other versions.
* https://docs.python.org/3/
* https://docs.python.org/3.13/

Remove statement about CPython 3.13 docs and fix typos

---

README.md

* Recommend scikit-build-core + pybind11.

docs: Update binary projects recommendation to scikit-build

---

_config.yml

fix: link back to learn/sp

---

{{cookiecutter.project_name}}/.github/workflows/ci.yml
{{cookiecutter.project_name}}/src/{{cookiecutter.__project_slug}}/__init__.py

Since 3.12 is stable, no need to have a default 3.11 job too. Minor touchups.

chore: drop 3.11 & use pypy3.10

---

README.md
docs/pages/guides/style.md
pyproject.toml
src/sp_repo_review/checks/ruff.py
{{cookiecutter.project_name}}/pyproject.toml

Noticed in https://github.com/astral-sh/ruff/pull/8035.
Also looking for `tool.ruff.lint`.
Now supports `ruff.toml` and `.ruff.toml` too.

feat: check for deprecated Ruff codes

---

src/sp_repo_review/checks/precommit.py

Bug exposed by adding a second hook (#299).

fix: fix logic broken if more than one hook in Ruff

---

.pre-commit-config.yaml
README.md
docs/pages/guides/style.md
pyproject.toml
src/sp_repo_review/checks/general.py
src/sp_repo_review/checks/github.py
src/sp_repo_review/checks/precommit.py
src/sp_repo_review/checks/pyproject.py
src/sp_repo_review/checks/ruff.py
{{cookiecutter.project_name}}/pyproject.toml

Ruff-formatter seems to be [ready](https://astral.sh/blog/the-ruff-formatter). This doesn't change the default for the cookie yet, but mentions it in a tab, and allows it in sp-repo-review.

feat: allow and mention ruff-formatter

---

docs/_includes/interactive_repo_review.html
docs/pages/guides/style.md
pyproject.toml
{{cookiecutter.project_name}}/.pre-commit-config.yaml
{{cookiecutter.project_name}}/pyproject.toml

Simplified the Ruff config.
Will release after this.

fix: simplify and prepare for next release

---

docs/pages/guides/tasks.md
src/sp_repo_review/checks/general.py

This supports a few more task runners. SPIN doesn't support environments, so I'm not sure it should be listed in this check, but probably doesn't hurt to include it.

fix: support hatch, tox (pyproject), and spin for PY007

---

README.md
docs/pages/guides/style.md
pyproject.toml
src/sp_repo_review/checks/mypy.py
{{cookiecutter.project_name}}/pyproject.toml

This has been deprecated for quite a while and I just noticed it when working on https://github.com/python/mypy/issues/16491.

fix: show_error_codes deprecated

---

.pre-commit-hooks.yaml
README.md

Nicer default for projects that aren't using `additional_dependencies`.

fix: nicer default for pre-commit hook

---

src/sp_repo_review/checks/pyproject.py

This loosens the required flag; any flag is fine, not just `-ra`; that
indicates you know what summary level you want rather than taking the default.
See https://github.com/astropy/astropy/pull/15367.

fix: loosen required summary flag

---

pyproject.toml
src/sp_repo_review/checks/ruff.py
tests/packages/ruff_extend/pyproject.toml
tests/packages/ruff_extend/ruff.toml
tests/test_package.py
tests/test_utils.py

Fix #311. Currently only top level configuration supported, but that that's what the checks are mostly targeting anyway.
Also added a test for `ALL` & extend.

fix: support simple Ruff extend

---

docs/_includes/pyproject.md
noxfile.py
{{cookiecutter.project_name}}/pyproject.toml

Fixing https://github.com/scientific-python/cookie/issues/319. Let's see if it's safe to add this field to all backends. I checked three of them so far.

fix: add license file and test

---

docs/pages/guides/gha_pure.md
{{cookiecutter.project_name}}/.github/workflows/{% if cookiecutter.__type!='compiled' %}cd.yml{% endif %}

Typo pointed out by @andrzejnovak.

fix: use build-and-inspect-packages, fix typo in guide

---

docs/pages/tutorials/index.md

Looks like this sentence was in the midst of being reworded, and some bits got left out. Here's one possible way to finish the sentence.
I would open a issue and all that, but I figured I'd just propose the small change like this. Feel free to edit as you see fit, or fix it in a separate work.
Heard about this guide on Real Python from October 27th, thanks for putting resources towards this, it will be a good resource for my colleagues.

Reword an incomplete sentence in tutorial intro

---

src/sp_repo_review/checks/general.py

The added filenames are LICENCE and COPYING, both of which are commonly used. There might be others accepted by GitHub, but the list can easily be extended.
This check could be a little slower due to having to do three times the number of string comparisons, but hopefully that is counteracted by the switch to using a generator, ensuring that an intermediate list doesn't have to be built, and that the check can terminate as soon as a file is found.
Fixes https://github.com/scientific-python/cookie/issues/326

fix: accept other filenames for LICENSE

---

{{cookiecutter.project_name}}/.github/CONTRIBUTING.md

The command shown in the `Contributing` guide was not matching the actual command from the `noxfile`.
This PR makes it consistent.
Let me know if you would prefer to change the noxfile parameter instead.

fix: docs serve command

---

.github/workflows/reusable-cookie.yml
docs/pages/guides/gha_pure.md
docs/pages/guides/gha_wheels.md
{{cookiecutter.project_name}}/.github/workflows/{% if cookiecutter.__type=='compiled' %}cd.yml{% endif %}

I can't actually start suggesting v4 until @hynek's build-and-inspect-python-package updates, since we suggest using that for pure Python packages, and v1-v3 upload/download is not cross compatible with v4. Features of v4 are here: https://github.com/actions/toolkit/tree/main/packages/artifact#v2---whats-new - sounds nice, though the immutable artifacts is a hard one (see https://github.com/pypa/cibuildwheel/issues/1699 too). There's an issue asking for guidance here: https://github.com/actions/upload-artifact/issues/472.

fix: prepare for artifact v4

---

noxfile.py

Fix for #345, regex's need a leading `~`.

ci: fix syntax for regex

---

.github/dependabot.yml
README.md
docs/pages/guides/gha_basic.md
src/sp_repo_review/checks/github.py
{{cookiecutter.project_name}}/.github/dependabot.yml

This adds dependabot grouping and matching check.
- ci: group dependabot updates
- feat: grouped updates for Dependabot

feat: groups for dependabot

---

README.md
docs/pages/guides/gha_basic.md
docs/pages/guides/gha_pure.md
docs/pages/guides/gha_wheels.md
src/sp_repo_review/checks/github.py
{{cookiecutter.project_name}}/.github/workflows/{% if cookiecutter.__type!='compiled' %}cd.yml{% endif %}
{{cookiecutter.project_name}}/.github/workflows/{% if cookiecutter.__type=='compiled' %}cd.yml{% endif %}

Support for https://github.com/actions/upload-artifact/issues/472.

feat: support archive v4

---

pyproject.toml

I think this was a replacement mistake when moving over. This the the homepage for sp-repo-review, so linking to the GitHub page seems to make sense.
Fix #331.
Not sure what the best way to check for this might be, might be something a link check tool could support?

docs: fix link to homepage

---

src/sp_repo_review/checks/mypy.py

Noticed in https://github.com/scikit-hep/vector/pull/408.

fix: allow warn_unreachable to be set to False explicitly

---

docs/pages/guides/packaging_classic.md

Hi, this PR is a _minor_ documentation fix – I was just reading through [the section **"Including/excluding files in the SDist"** in the **Classic Packaging** guide](https://learn.scientific-python.org/development/guides/packaging-classic/#includingexcluding-files-in-the-sdist) and this point caught my eye: this section talks about the procedure used to install a package via the invocation of the `pip install .` command: it incorrectly refers to the wheel as being a `.tar.gz` file while it isn't – it is fairly and commonly known that it is a `.zip` file. 
I have mentioned the correct file extension for the wheel and added a note about the SDist being in a sentence above, correctly reporting so that it can be known that the difference exists. I don't think that the incorrect documentation …

docs: assert correct file extension reference for wheels & sdists

---

docs/pages/guides/packaging_compiled.md
{{cookiecutter.project_name}}/{% if cookiecutter.backend=='mesonpy' %}meson.build{% endif %}

- Use `dependency('pybind11')`, which is all that is needed since Meson 1.1.0,
- Don't define an unused `py_mod` Python module,
- Remove custom C++ compile flags that are not present in the scikit-build-core and Maturin examples (nor seem needed),
- Make indentation consistent,
- ~~Use `py.install_sources` instead of a more complicated `install_subdir` call,~~

Make meson-python usage example more idiomatic

---

pyproject.toml

This makes it easier to run with schema validation enabled.

chore: add pyproject extra

---

docs/pages/tutorials/module.md

I found a dangling todo in the inline documentation section which should (I guess?) link to the writing documentation section. Ping me if it should have linked to the topical guide on writing documentation instead (they both have the same name).
You might want to check if the link works correctly. I have some ruby build issues locally and already spend too much time on it for a single line docs fix on a Sunday :) So i could not check it. 
Anyways, thanks for building this resource!

Replace ToDo with link to `Writing documentation` in `Inline Documentation` tutorial

---

docs/pages/guides/repo_review.md
src/sp_repo_review/checks/mypy.py
src/sp_repo_review/checks/ruff.py

Small improvement for unneeded config.

fix: error if both target-version and project.requires-python are set

---

src/sp_repo_review/checks/pyproject.py
tests/test_checks.py

See https://github.com/astropy/astropy/pull/16253.

fix(rr): pytest takes ints and floats

---

README.md
noxfile.py

Reverts scientific-python/cookie#399
Fixed three days ago in copier.

Revert "ci: copier pyyaml-include issue"

---

.github/workflows/reusable-cookie.yml
.github/workflows/reusable-rr-tests.yml
{{cookiecutter.project_name}}/.github/workflows/ci.yml
{{cookiecutter.project_name}}/.github/workflows/{% if cookiecutter.__type=='compiled' %}cd.yml{% endif %}
{{cookiecutter.project_name}}/pyproject.toml

macos-latest now points to macos-14, which is ARM and doesn't have Python 3.8 and 3.9.

fix: support macos-14, avoid macos-latest

---

{{cookiecutter.project_name}}/.github/workflows/{% if cookiecutter.__type!='compiled' %}cd.yml{% endif %}

The job definition to which this step belongs already includes the same conditional.

Remove duplicate workflow YAML conditional

---

.github/workflows/reusable-cookie.yml
{{cookiecutter.project_name}}/.github/workflows/ci.yml

ci: use macos-14's new Python 3.8+ support

---

docs/pages/guides/docs.md
docs/pages/guides/tasks.md
docs/pages/tutorials/dev-environment.md
{{cookiecutter.project_name}}/.readthedocs.yaml
{{cookiecutter.project_name}}/README.md
{{cookiecutter.project_name}}/noxfile.py

Cleanup docs a bit, faster option.

feat: add uv readthedocs config

---

{{cookiecutter.project_name}}/{% if cookiecutter.license=='Apache' %}LICENSE{% endif %}

I believe the appendix is actually supposed to have the brackets there and no year+name substitution already done.
I think it might also be okay to omit the appendix? But better not if github includes it by default
Close #428

remove template variables from apache license appendix

---

.pre-commit-config.yaml
README.md
docs/pages/guides/docs.md
src/sp_repo_review/checks/precommit.py
{{cookiecutter.project_name}}/docs/conf.py

closes https://github.com/scientific-python/summit-2024/issues/16

update theme-related text in documentation guide

---

.git_archival.txt
docs/pages/guides/packaging_classic.md
docs/pages/guides/packaging_simple.md
{{cookiecutter.project_name}}/.git_archival.txt

Howdy! @webknjaz recently posted about this issue with `ref-names` on a package I maintain, so I thought I’d also submit a change the recommendations/instructions/templates here (where I think I originally learned about `.git_archival.txt`).
It turns out that the `ref-names` field in `.git_archival.txt` will generate a different value depending on whether the commit that an archive was built from was the head of a branch *at the time of archiving.* That's a problem because it means someone trying to compare the hash digests of two archives built from the same commit might get different results based on *when* the archives were made, and not on any other intrinsic feature of the archives' content (e.g. if I wanted to verify a published archive from an official release of a package against …

Remove `ref-names` from `.git_archival.txt`

---

.github/workflows/cd.yml
docs/pages/guides/gha_pure.md
docs/pages/guides/gha_wheels.md
{{cookiecutter.project_name}}/.github/workflows/{% if cookiecutter.__type!='compiled' %}cd.yml{% endif %}
{{cookiecutter.project_name}}/.github/workflows/{% if cookiecutter.__type=='compiled' %}cd.yml{% endif %}

Generally available, so adding them to the template.

feat: add attestations

---

.pre-commit-config.yaml
src/sp_repo_review/checks/mypy.py

Both look acceptable, but falsy is is more common than falsey, especially in contemporary English:
https://books.google.com/ngrams/graph?content=falsy%2Cfalsey&year_start=1800&year_end=2019&corpus=en-2019

falsey → falsy

---

src/sp_repo_review/checks/precommit.py

I'm a little worried about the development (hasn't been touched in months), and I don't like the plugin system not letting you list plugins, but I think it's fine if someone uses it, so adding it to the checks. If some of my concerns are addressed, then we could add it as a suggested alternative in the future.

fix: allow mdformat as a mdformatter

---

src/sp_repo_review/checks/pyproject.py
tests/test_pyproject.py

Fix https://github.com/scientific-python/cookie/issues/465 by allowing this to be a string. Pytest just transforms arrays into strings (same way cibuildwheel works, actually), so either is supported; reflect this in the check. The other checks look fine, and should support a string due to the way `in` works.

fix: allow pytest opts to be a string

---

README.md
docs/pages/guides/style.md
pyproject.toml
src/sp_repo_review/checks/ruff.py

Flips this check now that Ruff defaults to `["src"]`. Also update docs on Jupyter notebooks and Ruff, since that's now default.

fix: support for Ruff 0.6

---

src/sp_repo_review/checks/github.py

Fix #485. Both names seem to be supported. Hopefully I got the order correct, but someone shouldn't have both anyway. :)

fix: support .yaml for dependabot too

---

.github/workflows/reusable-cookie.yml
docs/pages/guides/gha_basic.md
docs/pages/guides/tasks.md

ci: use astral-sh/setup-uv

---

.pre-commit-config.yaml
README.md
docs/pages/guides/packaging_simple.md
src/sp_repo_review/checks/pyproject.py
src/sp_repo_review/checks/ruff.py
tests/test_pyproject.py

Adding an upper-cap check for requires-python.

feat: upper cap check

---

{{cookiecutter.project_name}}/pyproject.toml

This makes `uv run pytest` or `uv run --python 3.13 pytest` work out of the box.

chore: support uv run

---

docs/_includes/pyproject.md
docs/pages/guides/packaging_simple.md
{{cookiecutter.project_name}}/pyproject.toml

This doesn't work correctly, it sets the License metadata field, which is supposed to describe the deviation from the classifiers, not contain a whole license. PEP 639 finally fixes this using SPDX classifiers.

fix: don't set license.file

---

src/sp_repo_review/checks/general.py
tests/test_general.py

The `sp-repo-review` checks for the existence of the `tests` (PY005) and `docs` (PY004) directories are too lenient and often return false positives.
The existence of a file or directory in the repo that _contains_ the word "docs" or "tests" will result in a pass for these tests.
For example, the existence of the `.readthedocs` file causes the `PY004 Has docs folder` test to pass, simply because it contains the work `docs`. Similarly, an innocuously named file such as `fastest.txt` would result in a false pass of `PY005 Has tests folder`.
This PR modifies the `PY004` and `PY005` checks to:
- Compare against string `tests` or `docs`, rather than testing if the filename contains that string.
- Require that the path is a directory
- `test` is no longer a match for PY005: should be `tests` as …

bugfix: Stricter check for "tests" and "docs" directories in sp-repo-review 

---

README.md
docs/_includes/interactive_repo_review.html

Signed-off-by: Henry Schreiner <henryschreineriii@gmail.com>

chore: bump webapp & README

---

README.md

docs: update mention of ignores

---

README.md
docs/_includes/pyproject.md
pyproject.toml
src/sp_repo_review/checks/pyproject.py
tests/packages/ruff_extend/ruff.toml
tests/test_pyproject.py

It should be fairly self explanatory.
I think maybe we can now recommand License-Expression in favor of License when possible.

Add check that Deprecated Trove classifiers are not used.

---

docs/pages/guides/tasks.md
{{cookiecutter.project_name}}/noxfile.py

See #566. Let see if any backends have issues. We already had it in the docs job, and the one backend I know about that it used to not work should be removed now. Edit: Looks like mesonpy doesn't handle editable installs very well, that's the blocker.

fix: use -e in more places in the noxfile

---

docs/pages/guides/docs.md

This is needed to support notebooks. Found by @bcaddy.

docs: add ipykernel to docs

---

.pre-commit-config.yaml
docs/pages/guides/style.md
noxfile.py
{{cookiecutter.project_name}}/.github/workflows/ci.yml
{{cookiecutter.project_name}}/noxfile.py

I think they style themselves as Pylint or pylint - see https://github.com/pylint-dev/pylint or https://pylint.readthedocs.io/en/latest/
> What is Pylint?

Rename PyLint -> Pylint

---

.gitignore
README.md
docs/pages/guides/packaging_classic.md
docs/pages/guides/packaging_simple.md
pyproject.toml
src/sp_repo_review/checks/setupcfg.py
src/sp_repo_review/families.py
tests/test_setupcfg.py

This was rolled back in setuptools 78.0.2, but is targeting 2026. Let's check for it.
See https://github.com/pypa/setuptools/pull/4911 and related PRs/issues.

feat: check for deprecated setup.cfg settings

---

.github/workflows/reusable-rr-tests.yml
noxfile.py
pyproject.toml

Pip 25.1 supports `--group` now too, so starting to transition here. First moving sp-repo-review.

chore: use uv and dependency-groups

---

src/sp_repo_review/families.py
tests/test_families.py

Support PEP 639 in the license detection.

fix: detect SPDX licenses too

---

README.md
docs/_includes/pyproject.md
docs/pages/guides/docs.md
docs/pages/guides/gha_basic.md
docs/pages/guides/gha_wheels.md
docs/pages/guides/tasks.md
noxfile.py
{{cookiecutter.project_name}}/.github/CONTRIBUTING.md
{{cookiecutter.project_name}}/.github/workflows/ci.yml
{{cookiecutter.project_name}}/.github/workflows/{% if cookiecutter.__type=='compiled' %}cd.yml{% endif %}
{{cookiecutter.project_name}}/.readthedocs.yaml
{{cookiecutter.project_name}}/noxfile.py
{{cookiecutter.project_name}}/pyproject.toml
{{cookiecutter.project_name}}/{% if cookiecutter.__ci=='gitlab' %}.gitlab-ci.yml{% endif %}

Now that pip supports it, probably time to move.
I can look at adding pip/uv/pipx toggles in a few places.

feat: use uv and dependency-groups

---

docs/_includes/pyproject.md
noxfile.py
pyproject.toml
{{cookiecutter.project_name}}/pyproject.toml

Supported:
* `hatchling>=1.26`
* `flit-core>=1.11`
* `pdm-backend>=2.4`
* `setuptools>=77`
* `scikit-build-core>=0.12`
Currently the only backends that haven't supported this yet:
* Maturin (in progress in https://github.com/PyO3/maturin/pull/2571)
* Meson-python (in https://github.com/mesonbuild/meson-python/pull/681, unreleased)
* Poetry-core (produces Metadata 2.3 when configured! Support issue: https://github.com/python-poetry/poetry/issues/9670)
Close #589.

feat: use PEP 639 where possible

---

.github/workflows/docs-link.yml

Not a huge fan of adding links when it's also in the checks list, but I want to test this out and for something that's mostly docs, it's not a bad idea.

ci: add links to rendered docs

---

.pre-commit-config.yaml
docs/pages/guides/style.md
pyproject.toml
{{cookiecutter.project_name}}/.pre-commit-config.yaml

See https://github.com/pypa/packaging/pull/910.
We could add a check for this to sp-repo-review in the future.
----
📚 Documentation preview 📚: https://scientific-python-cookie--602.org.readthedocs.build/

fix: move codespell config to toml

---

.github/workflows/reusable-cookie.yml
docs/pages/guides/packaging_compiled.md
{{cookiecutter.project_name}}/.github/workflows/ci.yml

Follow for https://github.com/actions/setup-python/issues/1123, include template.
----
📚 Documentation preview 📚: https://scientific-python-cookie--613.org.readthedocs.build/

fix: Python 3.13.4 broken on Windows

---

noxfile.py

Noticed one test we should be able to update after #622.
----
📚 Documentation preview 📚: https://scientific-python-cookie--623.org.readthedocs.build/

chore: update a test for license change

---

src/sp_repo_review/checks/precommit.py
tests/test_precommit.py

New Rust-based MD formatter from @rvben.
Also handling the rename of mdformat.
----
📚 Documentation preview 📚: https://scientific-python-cookie--631.org.readthedocs.build/

fix: add a new md formatter

---

.github/release.yml
docs/pages/guides/gha_basic.md
{{cookiecutter.project_name}}/.github/release.yml

It seems github changed the way the exclusion from auto-generated release notes works, such that this has to match what is displayed as author.
In other words, the only way I could get it to exclude the bots was to include the `[bot]` suffix for bots like `pre-commit-ci` and `dependabot`.
(not sure if I did something wrong, though)
----
📚 Documentation preview 📚: https://scientific-python-cookie--636.org.readthedocs.build/

change the exclusion pattern for bots

---

docs/pages/principles/testing.md

This PR contains an outline of a proposed Development Guide / Principles / Unit Testing Recommendations section.
I am opening this PR now to allow discussion of the outline, and key-points, before fleshing out the complete page.
----
📚 Documentation preview 📚: https://scientific-python-cookie--619.org.readthedocs.build/

docs: Add outline of unit testing recommendations
