scientific-python/cookie

{{cookiecutter.project_name}}/.github/CONTRIBUTING.md, {{cookiecutter.project_name}}/.github/workflows/ci.yml, {{cookiecutter.project_name}}/.gitignore, {{cookiecutter.project_name}}/.readthedocs.yml, {{cookiecutter.project_name}}/README.md, {{cookiecutter.project_name}}/pyproject-flit.toml, {{cookiecutter.project_name}}/pyproject-poetry.toml, {{cookiecutter.project_name}}/setup.cfg
Fixed #2.
* It looks like a .gitignore is not included.
* The CONTRIBUTING should have specific instructions for Poetry (and flit, if needed).
* There should be a docs extra and test extra
* Maybe include a .readthedocs.yml
* CI shouldn't do editable installs.
* check-manifest doesn't work with other systems, drop from setup.cfg
=> fix: some fixes from uhi

{{cookiecutter.project_name}}/.pre-commit-config.yaml, {{cookiecutter.project_name}}/setup.cfg
Cross-ref: https://github.com/scikit-hep/scikit-hep.github.io/pull/122
=> style: adding setup-cfg-fmt

{{cookiecutter.project_name}}/setup.cfg
CC https://github.com/scikit-hep/scikit-hep.github.io/pull/126
=> docs: add project links

{{cookiecutter.project_name}}/pyproject-pybind11.toml, {{cookiecutter.project_name}}/pyproject-setuptools.toml, {{cookiecutter.project_name}}/setup.cfg, {{cookiecutter.project_name}}/src/{{cookiecutter.project_name}}/__init__.py
CC https://github.com/scikit-hep/scikit-hep.github.io/pull/133
=> refactor: version -> _version

noxfile.py, tests/flit.yml, tests/poetry.yml, tests/pybind11.yml, tests/setuptools.yml
Simpler using nox to write the file, followup to #19.
=> ci: write context file

{{cookiecutter.project_name}}/.github/workflows/ci.yml
Fixes #24, thanks to @phinate!
=> fix(ci): typo in default CI

noxfile.py
By making the result a real git repo in nox, this simplifies the rest of the checks, and lets the auto versioning workarounds be removed. Except for a bug in trampolim, see https://github.com/FFY00/trampolim/issues/4.
=> fix: poetry was confused by the parent git

{{cookiecutter.project_name}}/.gitignore
=> fix: corrected version file gitignore

.github/workflows/ci.yml, README.md, cookiecutter.json, hooks/post_gen_project.py, noxfile.py, {{cookiecutter.project_name}}/pyproject-flit621,trampolim,whey.toml
Adding whey support, since it's PEP 621 as well.
=> feat: add whey support (PEP 621)

.github/workflows/ci.yml, README.md, noxfile.py, {{cookiecutter.project_name}}/.github/CONTRIBUTING.md, {{cookiecutter.project_name}}/.pre-commit-config.yaml, {{cookiecutter.project_name}}/docs/conf.py, {{cookiecutter.project_name}}/pyproject-flit.toml, {{cookiecutter.project_name}}/pyproject-flit621,trampolim,whey.toml, {{cookiecutter.project_name}}/pyproject-poetry.toml, {{cookiecutter.project_name}}/setup-setuptools,pybind11.cfg
Counterpart to https://github.com/scikit-hep/scikit-hep.github.io/pull/146.
=> feat: spelling, fix docs

{{cookiecutter.project_name}}/.pre-commit-config.yaml
Reverts scikit-hep/cookie#53, closes #52.
=> Revert "fix: disable pycln"

.github/workflows/ci.yml, README.md, {{cookiecutter.project_name}}/.github/workflows/ci-pybind11.yml, {{cookiecutter.project_name}}/.github/workflows/ci-trampolim.yml, {{cookiecutter.project_name}}/.github/workflows/ci.yml, {{cookiecutter.project_name}}/.pre-commit-config.yaml, {{cookiecutter.project_name}}/docs/conf.py, {{cookiecutter.project_name}}/noxfile.py, {{cookiecutter.project_name}}/pyproject-flit,pdm,trampolim,whey.toml, {{cookiecutter.project_name}}/pyproject-poetry.toml, {{cookiecutter.project_name}}/pyproject-pybind11.toml, {{cookiecutter.project_name}}/pyproject-setuptools.toml, {{cookiecutter.project_name}}/setup-pybind11.py, {{cookiecutter.project_name}}/setup-setuptools,pybind11.cfg, {{cookiecutter.project_name}}/setup-setuptools.py, {{cookiecutter.project_name}}/src/{{cookiecutter.project_name}}/__init__.py, {{cookiecutter.project_name}}/tests/test_package.py
=> chore: drop 3.6

.github/workflows/ci.yml, README.md, cookiecutter.json, hooks/post_gen_project.py, noxfile.py, {{cookiecutter.project_name}}/pyproject^setuptools,pybind11,poetry.toml
The last hatchling release or two fixed the main problems.
Closes #66
=> feat: add hatch/hatchling

README.md, {{cookiecutter.project_name}}/.github/matchers/pylint.json, {{cookiecutter.project_name}}/.github/workflows/ci-pybind11.yml, {{cookiecutter.project_name}}/.github/workflows/ci-trampolim.yml, {{cookiecutter.project_name}}/.github/workflows/ci.yml, {{cookiecutter.project_name}}/noxfile.py, {{cookiecutter.project_name}}/pyproject-poetry.toml, {{cookiecutter.project_name}}/pyproject-pybind11.toml, {{cookiecutter.project_name}}/pyproject-setuptools.toml, {{cookiecutter.project_name}}/pyproject^setuptools,pybind11,poetry.toml, {{cookiecutter.project_name}}/src/{{cookiecutter.project_name}}/__init__.py
Partner PR: https://github.com/scikit-hep/scikit-hep.github.io/pull/176
=> feat: add pylint

{{cookiecutter.project_name}}/.pre-commit-config.yaml
Fix for https://github.com/pre-commit/mirrors-clang-format/pull/10 and counterpart to https://github.com/scikit-hep/scikit-hep.github.io/pull/179.
=> chore: bump pre-commit and add types_or

{{cookiecutter.project_name}}/.pre-commit-config.yaml, {{cookiecutter.project_name}}/pyproject-poetry.toml, {{cookiecutter.project_name}}/pyproject-pybind11.toml, {{cookiecutter.project_name}}/pyproject-setuptools.toml, {{cookiecutter.project_name}}/pyproject^setuptools,pybind11,poetry.toml
=> fix: use all flag instead of config for pycln

{{cookiecutter.project_name}}/.pre-commit-config.yaml, {{cookiecutter.project_name}}/pyproject-poetry.toml, {{cookiecutter.project_name}}/pyproject-pybind11.toml, {{cookiecutter.project_name}}/pyproject-setuptools.toml, {{cookiecutter.project_name}}/pyproject^setuptools,pybind11,poetry.toml
X-ref: https://github.com/scikit-hep/scikit-hep.github.io/pull/191
=> feat: extra mypy typing, better config

{{cookiecutter.project_name}}/.pre-commit-config.yaml
See https://github.com/psf/black/issues/2964 for details.
=> style: bump black

{{cookiecutter.project_name}}/.pre-commit-config.yaml
Signed-off-by: Henry Schreiner <henryschreineriii@gmail.com>
=> chore: bump pre-commit versions

README.md, noxfile.py
=> chore: use hatch 1

.github/workflows/ci.yml, README.md, {{cookiecutter.project_name}}/.github/workflows/ci-pybind11.yml, {{cookiecutter.project_name}}/.github/workflows/ci-trampolim.yml, {{cookiecutter.project_name}}/.github/workflows/ci.yml, {{cookiecutter.project_name}}/.github/workflows/wheels-pybind11.yml
=> ci: update to pypy 3.8 and v3

.github/workflows/ci.yml, {{cookiecutter.project_name}}/.github/workflows/ci-pybind11.yml, {{cookiecutter.project_name}}/.github/workflows/ci-trampolim.yml, {{cookiecutter.project_name}}/.github/workflows/ci.yml, {{cookiecutter.project_name}}/.github/workflows/wheels-pybind11.yml
Already in the dev guidelines.
=> chore: add auto-cancel

LICENSE, README.md, cookiecutter.json, noxfile.py, {{cookiecutter.project_name}}/LICENSE, {{cookiecutter.project_name}}/README.md, {{cookiecutter.project_name}}/pyproject^setuptools,pybind11,skbuild,poetry.toml
=> feat: add license selection

{{cookiecutter.project_name}}/.pre-commit-config.yaml
X-ref https://github.com/scikit-hep/scikit-hep.github.io/pull/251
=> fix: Version 2 of setup-cfg-fmt requires a new flag

{{cookiecutter.project_name}}/.github/CONTRIBUTING.md, {{cookiecutter.project_name}}/.github/workflows/ci.yml, {{cookiecutter.project_name}}/noxfile.py, {{cookiecutter.project_name}}/pyproject-poetry.toml, {{cookiecutter.project_name}}/pyproject^setuptools,pybind11,skbuild,poetry.toml, {{cookiecutter.project_name}}/setup-setuptools,pybind11,skbuild.cfg
Closes #99 
Please let me know if I am missing a file!
=> feat: add support for coverage

{{cookiecutter.project_name}}/.git_archival.txt, {{cookiecutter.project_name}}/.gitattributes
X-ref https://github.com/scikit-hep/scikit-hep.github.io/pull/250
=> feat: add git archive support for auto versioning

{{cookiecutter.project_name}}/.flake8^setuptools,pybind11, {{cookiecutter.project_name}}/setup-setuptools,pybind11,skbuild.cfg
Simpler, especially if plugins are added or removed.
=> fix: use extend-select for flake8

{{cookiecutter.project_name}}/.pre-commit-config.yaml, {{cookiecutter.project_name}}/pyproject-poetry.toml, {{cookiecutter.project_name}}/pyproject-pybind11,skbuild.toml, {{cookiecutter.project_name}}/pyproject-setuptools.toml, {{cookiecutter.project_name}}/pyproject^setuptools,pybind11,skbuild,poetry.toml
A repo created from this may fail repo-review. Fixed.
=> fix: pass repo-review

{{cookiecutter.project_name}}/pyproject-poetry.toml, {{cookiecutter.project_name}}/pyproject-pybind11,skbuild.toml, {{cookiecutter.project_name}}/pyproject-setuptools.toml, {{cookiecutter.project_name}}/pyproject^setuptools,pybind11,skbuild,poetry.toml
Nicer default for hatchling; since this is our default, worth setting it up.
=> feat: use hatch source versioning

cookiecutter.json, {{cookiecutter.project_name}}/README.md, {{cookiecutter.project_name}}/docs/conf.py, {{cookiecutter.project_name}}/pyproject-poetry.toml, {{cookiecutter.project_name}}/pyproject^setuptools,pybind11,skbuild,poetry.toml, {{cookiecutter.project_name}}/setup-setuptools,pybind11,skbuild.cfg
Simpler, and likely not useful to most.
=> fix: drop maintainer setting

{{cookiecutter.project_name}}/pyproject-poetry.toml, {{cookiecutter.project_name}}/pyproject^setuptools,pybind11,skbuild,poetry.toml, {{cookiecutter.project_name}}/setup-setuptools,pybind11,skbuild.cfg
Some issues with some backends.
=> fix: license and URL fixes

{{cookiecutter.project_name}}/.github/workflows/ci.yml, {{cookiecutter.project_name}}/.github/workflows/wheels-pybind11,skbuild,maturin.yml
Was included in cookie's own CI, but not in the generated CI.
=> fix: support color in the CI runs

{{cookiecutter.project_name}}/setup-skbuild.py
Oops, followup to #108 fixing #98.
=> fix: include py.typed

.github/workflows/ci.yml, noxfile.py, {{cookiecutter.project_name}}/.github/workflows/ci.yml, {{cookiecutter.project_name}}/.github/workflows/wheels-pybind11,skbuild,maturin.yml, {{cookiecutter.project_name}}/.pre-commit-config.yaml, {{cookiecutter.project_name}}/pyproject^setuptools,pybind11,skbuild,poetry.toml, {{cookiecutter.project_name}}/setup-setuptools,pybind11,skbuild.cfg
Some updates too.
X-ref: https://github.com/scikit-hep/scikit-hep.github.io/pull/281
=> chore: Python 3.11 support

{{cookiecutter.project_name}}/.flake8^setuptools,pybind11, {{cookiecutter.project_name}}/noxfile.py, {{cookiecutter.project_name}}/pyproject-poetry.toml, {{cookiecutter.project_name}}/pyproject-pybind11,skbuild.toml, {{cookiecutter.project_name}}/pyproject-setuptools.toml, {{cookiecutter.project_name}}/pyproject^setuptools,pybind11,skbuild,poetry.toml, {{cookiecutter.project_name}}/setup-setuptools,pybind11,skbuild.cfg
This should run correctly now with built extensions. Also future safe with "master->main" conversion.
=> fix: pylint misconfiguration

{{cookiecutter.project_name}}/.pre-commit-config.yaml
Also added in https://github.com/scikit-hep/scikit-hep.github.io/pull/311.
=> chore: add recent --show-fixes addition to Ruff

{{cookiecutter.project_name}}/.pre-commit-config.yaml, {{cookiecutter.project_name}}/pyproject.toml, {{cookiecutter.project_name}}/setup-pybind11.py, {{cookiecutter.project_name}}/setup-setuptools.py
=> chore: some updates to Ruff based on dev pages

.github/workflows/ci.yml, README.md, {{cookiecutter.project_name}}/.pre-commit-config.yaml, {{cookiecutter.project_name}}/Cargo-maturin.toml, {{cookiecutter.project_name}}/src/lib-maturin.rs, {{cookiecutter.project_name}}/tests/test_compiled-pybind11,skbuild,maturin.py, {{cookiecutter.project_name}}/tests/test_package.py
Pulling changes from #124 that are unrelated to meson.
=> fix: maturin package structure

noxfile.py, {{cookiecutter.project_name}}/pyproject.toml
X-ref: https://github.com/pypa/packaging.python.org/pull/1220, https://github.com/scikit-hep/scikit-hep.github.io/pull/319.
Also removing skip due to https://github.com/pdm-project/pdm/issues/1411 being solved.
=> chore: update name of PDM backend

{{cookiecutter.project_name}}/.github/CONTRIBUTING.md, {{cookiecutter.project_name}}/.github/workflows/ci.yml, {{cookiecutter.project_name}}/.github/workflows/wheels-pybind11,skbuild,mesonpy,maturin.yml, {{cookiecutter.project_name}}/.gitignore, {{cookiecutter.project_name}}/.pre-commit-config.yaml, {{cookiecutter.project_name}}/pyproject.toml
Noticed a few things that needed touch up.
=> fix: minor updates and fixes from recent use

{{cookiecutter.project_name}}/.github/workflows/ci.yml, {{cookiecutter.project_name}}/noxfile.py, {{cookiecutter.project_name}}/pyproject.toml
=> fix: nicer coverage support

{{cookiecutter.project_name}}/.github/workflows/ci.yml, {{cookiecutter.project_name}}/.github/workflows/wheels-pybind11,skbuild,mesonpy,maturin.yml, {{cookiecutter.project_name}}/.pre-commit-config.yaml
Already shown in the dev pages.
=> feat: use pypi trusted publisher

.github/workflows/ci.yml, .github/workflows/reusable-change-detection.yml, .github/workflows/reusable-cookie.yml, .pre-commit-config.yaml, docs/README.md, docs/_includes/interactive_repo_review.html, docs/assets/js/webapp.js, docs/pages/guides/gha_pure.md, docs/pages/guides/mypy.md, hooks/post_gen_project.py, noxfile.py
- ci: better handling of changed files
- chore: add style checking
=> ci: style checking and file changed fixes

docs/_config.yml, docs/pages/patterns/data_files.md
related to #137
This PR adds recommended patterns for inclusion of data files in scientific python projects.
=> data file inclusion patterns

.pre-commit-config.yaml, README.md, docs/README.md, docs/pages/guides/coverage.md, docs/pages/guides/gha_basic.md, docs/pages/guides/gha_pure.md, docs/pages/guides/gha_wheels.md, docs/pages/guides/index.md, docs/pages/guides/mypy.md, docs/pages/guides/nox.md, docs/pages/guides/packaging_classic.md, docs/pages/guides/packaging_simple.md, docs/pages/guides/pytest.md, docs/pages/guides/repo_review.md, docs/pages/guides/style.md, docs/pages/index.md, docs/pages/patterns/data_files.md, docs/pages/principles/design.md, docs/pages/principles/index.md, docs/pages/principles/process.md, docs/pages/tutorials/dev-environment.md, docs/pages/tutorials/module.md, docs/pages/tutorials/packaging.md, docs/pages/tutorials/test.md
=> style: format markdown with prettier

docs/pages/patterns/index.md
Signed-off-by: Henry Schreiner <henryschreineriii@gmail.com>
=> fix: include somethign on the patterns index page

.github/workflows/reusable-cookie.yml, docs/README.md, docs/pages/guides/gha_basic.md, docs/pages/guides/nox.md, docs/pages/guides/packaging_classic.md, docs/pages/guides/packaging_simple.md, docs/pages/guides/pytest.md, docs/pages/guides/style.md, docs/pages/index.md, docs/pages/tutorials/index.md, noxfile.py, {{cookiecutter.project_name}}/.github/workflows/ci.yml, {{cookiecutter.project_name}}/pyproject.toml
=> feat: add Python 3.12 beta 1

.github/workflows/cd.yml, .github/workflows/ci.yml, .github/workflows/reusable-change-detection.yml, .github/workflows/reusable-rr-tests.yml, .pre-commit-config.yaml, docs/_includes/rr.html, docs/_sass/custom/custom.scss, docs/pages/guides/gha_basic.md, docs/pages/guides/nox.md, docs/pages/guides/packaging_classic.md, docs/pages/guides/packaging_simple.md, docs/pages/guides/pytest.md, docs/pages/guides/repo_review.md, docs/pages/guides/style.md, noxfile.py, pyproject.toml, src/sp_repo_review/__init__.py, src/sp_repo_review/_compat/importlib/resources/abc.py, src/sp_repo_review/_compat/tomllib.py, src/sp_repo_review/checks/__init__.py, src/sp_repo_review/checks/general.py, src/sp_repo_review/checks/github.py, src/sp_repo_review/checks/mypy.py, src/sp_repo_review/checks/precommit.py, src/sp_repo_review/checks/pyproject.py, src/sp_repo_review/checks/ruff.py, src/sp_repo_review/families.py, tests/test_cmd.py, tests/test_package.py
=> feat: add sp-repo-review

.git_archival.txt, .gitattributes, .github/workflows/cd.yml, .github/workflows/reusable-rr-tests.yml, .pre-commit-hooks.yaml, README-rr.md, README.md, action.yml, docs/_includes/interactive_repo_review.html, docs/assets/js/webapp.js, docs/pages/guides/gha_wheels.md, docs/pages/guides/style.md, noxfile.py, pyproject.toml, src/sp_repo_review/_version.pyi, src/sp_repo_review/checks/github.py
Updates for recommendation in repo-review docs & updates to repo-review.
Using SVN versioning for easy releases.
Also bumping versions & fixing bump jobs.
=> chore: update repo review handling

docs/_includes/interactive_repo_review.html, src/sp_repo_review/__init__.py
Internally reporting the wrong version.
=> fix: version number from correct place

.github/workflows/reusable-change-detection.yml
CI fix from #172. Supports spaces in filenames.
=> fix: format to json

docs/_includes/interactive_repo_review.html, docs/assets/js/webapp.js
=> chore: bump repo-review

README-rr.md, README.md, pyproject.toml
Little bit of cleanup, planning "release" soon.
=> docs: clean up a few references to scikit-hep, add a little attribution

README.md, copier.yml
A fix for copier validation & README updates for copier now that there's a release.
=> fix: copier org validation

_config.yml, docs/pages/guides/coverage.md, docs/pages/guides/gha_wheels.md, docs/pages/guides/packaging_simple.md, docs/pages/guides/pytest.md, docs/pages/guides/style.md, docs/pages/guides/tasks.md
Fixing the view-source link and a few other docs updates.
=> fix: some updates and minor fixes

docs/pages/guides/mypy.md
=> docs: add a typing tip

docs/pages/patterns/all.md
=> feat: page on setting __all__/__dir__

.github/workflows/reusable-cookie.yml, README.md, noxfile.py
=> docs: mention support for cruft

docs/_includes/toc.html, docs/pages/guides/coverage.md, docs/pages/guides/docs.md, docs/pages/guides/gha_basic.md, docs/pages/guides/gha_pure.md, docs/pages/guides/gha_wheels.md, docs/pages/guides/index.md, docs/pages/guides/mypy.md, docs/pages/guides/packaging_classic.md, docs/pages/guides/packaging_simple.md, docs/pages/guides/pytest.md, docs/pages/guides/repo_review.md, docs/pages/guides/style.md, docs/pages/guides/tasks.md, docs/pages/patterns/backports.md, docs/pages/patterns/data_files.md, docs/pages/patterns/exports.md, docs/pages/patterns/index.md, docs/pages/principles/design.md, docs/pages/principles/process.md, docs/pages/tutorials/dev-environment.md, docs/pages/tutorials/docs.md, docs/pages/tutorials/module.md, docs/pages/tutorials/packaging.md, docs/pages/tutorials/test.md
- fix: some pattern pages not showing up
- fix: normalize page titles and headings
Also starting with ToC closed instead of open.
=> fix: pattern pages missing

docs/_includes/interactive_repo_review.html, docs/pages/guides/index.md, docs/pages/index.md
This adds some extra links and color to the index pages.
=> fix: nicer landing pages

docs/pages/guides/gha_basic.md, docs/pages/patterns/exports.md
This reorganizes the pages a bit, adds the composite action example from the Scientific-Python developer summit, as well as several other new basic and advanced topics.
=> feat: add more GHA tips and tricks and examples

{{cookiecutter.project_name}}/.pre-commit-config.yaml
Follow up to #200. We should test the generated repo against sp-repo-review.
=> chore: update template for ruff move

.readthedocs.yaml, noxfile.py, {{cookiecutter.project_name}}/.pre-commit-config.yaml
Now these are together, share some work. Added caching of versions as it processes, so we don't ask for the same version twice.
=> ci: update more parts automatically

docs/pages/guides/packaging_classic.md, {{cookiecutter.project_name}}/{% if cookiecutter.backend in ['setuptools','pybind11'] %}MANIFEST.in{% endif %}
=> fix: avoid overreaching with default MANIFEST.in

.pre-commit-config.yaml, docs/pages/guides/style.md, noxfile.py
It would be nice to have pre-commit.ci, but might as well self-update too if we are updating in CI.
=> ci: update self pre-commit versions too

.pre-commit-config.yaml, docs/pages/guides/packaging_classic.md, docs/pages/patterns/data_files.md, pyproject.toml
=> fix: correction to URLs

.pre-commit-config.yaml, docs/pages/guides/coverage.md, docs/pages/guides/docs.md, docs/pages/guides/gha_pure.md, docs/pages/guides/gha_wheels.md, docs/pages/guides/packaging_compiled.md, docs/pages/guides/style.md, {{cookiecutter.project_name}}/{% if cookiecutter.backend=='skbuild' %}CMakeLists.txt{% endif %}
Some touchup, using cog in more places, and added mention of build-and-inspect-python-package.
=> fix: more cog & mention build-and-inspect-python-package

docs/_includes/interactive_repo_review.html, docs/pages/guides/index.md
=> chore: prepare for 2023.07.06

docs/pages/index.md
Mention the compiled page at the top level too.
=> docs: mention compiled page too

Gemfile, Gemfile.lock, _config.yml, docs/pages/guides/gha_basic.md, docs/pages/guides/packaging_simple.md, docs/pages/guides/style.md, docs/pages/principles/design.md
=> fix: some broken links fuond by html-proofer

docs/pages/index.md
Adds a little history box to the main page.
Closes #161.
=> docs: add a bit of history

docs/pages/guides/gha_wheels.md, {{cookiecutter.project_name}}/.github/workflows/{% if cookiecutter.__type=='compiled' %}cd.yml{% endif %}, {{cookiecutter.project_name}}/pyproject.toml
=> fix: include cibuildwheel config

docs/pages/guides/docs.md, docs/pages/guides/tasks.md, {{cookiecutter.project_name}}/noxfile.py
Followup to #231. See https://github.com/scientific-python/repo-review/pull/109 as well.
=> fix: support autobuild for quick rebuilds

.pre-commit-config.yaml
Don't see a way to turn it all the way off.
=> ci: reduce frequency (already updated by another ci job)

docs/_includes/interactive_repo_review.html, docs/assets/js/webapp.js
Applying fixes in repo-review.
=> fix: use repo-review 0.9.2

{{cookiecutter.project_name}}/{% if cookiecutter.__ci=='gitlab' %}.gitlab-ci.yml{% endif %}
This was broken if gitlab was being targeted.
=> fix: gitlab was broken

{{cookiecutter.project_name}}/.github/CONTRIBUTING.md
This PR fixes typo in `CONTRIBUTING.md` by removing the repeated word 'with'.
=> docs: remove repeated "with" in CONTRIBUTING.md

docs/pages/guides/style.md
=> docs: pull Python check parts out of PGH

.pre-commit-config.yaml, src/sp_repo_review/checks/precommit.py
=> fix: blacken docs renamed

src/sp_repo_review/checks/readthedocs.py
This suggestion was incorrect.
=> fix: correct suggestion for RtD

{{cookiecutter.project_name}}/.github/workflows/{% if cookiecutter.__type!='compiled' %}cd.yml{% endif %}
=> fix: cd file has an error for non-compiled projects

src/sp_repo_review/checks/pyproject.py
=> docs(sp-repo-review): fix suggestion

{{cookiecutter.project_name}}/.github/CONTRIBUTING.md
I'm also wondering if it wouldn't be good to include a markdown link checker with `cookie` (that's how I found this)
=> Fix broken link

docs/pages/guides/style.md, {{cookiecutter.project_name}}/.pre-commit-config.yaml
Add info about validating schemas.
=> feat: schema validation

docs/pages/guides/docs.md, docs/pages/guides/packaging_classic.md
Correcting a few empty and a moved link.
=> fix: correct some missing links

docs/pages/guides/index.md, docs/pages/index.md
I think this makes more sense / is more obvious.
=> docs: change linked text for sp-repo-review

docs/pages/guides/index.md
=> fix: link was not copied properly

noxfile.py, {{cookiecutter.project_name}}/pyproject.toml
=> fix: tweak the hatch integration

docs/pages/guides/style.md
This page covers more than style, so adding to the name. URL is the same.
=> docs: improve page name

.pre-commit-config.yaml, docs/_includes/interactive_repo_review.html, docs/assets/js/webapp.js, docs/pages/guides/style.md, noxfile.py, {{cookiecutter.project_name}}/.pre-commit-config.yaml
Still have a bug with the gha update updating to old nox.
=> chore: clean up pre-commit update job a little

docs/pages/index.md
=> fix: grant, not coop agreement

noxfile.py
This should help with mirrors-prettier updating with pre-releases.
=> ci: filter pre-releases

docs/pages/tutorials/packaging.md
Fixes #340 (and duplicate #344).
=> fix: correct tutorial src layout (#340)

src/sp_repo_review/checks/github.py
This was "passing" on pipx, when in fact it should have failed. I've added matrix logic to detect that case.
This also fixes the error message (`{{` was being replaced with `{`).
=> fix: include matrix logic & location of errors in GH104

docs/pages/guides/packaging_simple.md
Fix links of PY rules in packaging_simple.md.
=> docs: fix links of PY rules in packaging_simple.md

docs/_includes/interactive_repo_review.html, docs/pages/guides/style.md, noxfile.py, {{cookiecutter.project_name}}/.pre-commit-config.yaml, {{cookiecutter.project_name}}/pyproject.toml
=> chore: add validate-pyproject-schema-store

README.md, docs/pages/guides/gha_wheels.md, docs/pages/guides/packaging_classic.md, docs/pages/guides/packaging_compiled.md, src/sp_repo_review/checks/github.py
Noticed some old text when updating for new Apple Silicon runners.
=> docs: modernize some of the pages

docs/pages/guides/repo_review.md
I think it makes it a bit more discoverable.
=> docss: move repo review up a page

README.md
Thanks for a great repo template! Minor update to README.
=> Switch from black to ruff formatter in README.md

src/sp_repo_review/checks/pyproject.py
=> fix: allow patch versions in min version

.github/workflows/reusable-cookie.yml, docs/pages/guides/gha_basic.md, docs/pages/guides/tasks.md, docs/pages/tutorials/dev-environment.md, noxfile.py, {{cookiecutter.project_name}}/noxfile.py
=> ci: use uv, require recent nox

README.md, noxfile.py
See https://github.com/copier-org/copier/issues/1568 and https://github.com/scientific-python/cookie/issues/396.
=> ci: copier pyyaml-include issue

src/sp_repo_review/checks/ruff.py, tests/test_ruff.py
=> fix: correct logic for RF002

.pre-commit-config.yaml, pyproject.toml, tests/test_pyproject.py, tests/test_ruff.py
=> tests: use most recent repo-review in testing

.github/release.yml, .pre-commit-config.yaml, docs/pages/guides/gha_basic.md, {{cookiecutter.project_name}}/.github/release.yml
I'm not adding a repo-review check as this is only useful if you use this as part of your release workflow.
=> feat: add GitHub release config

docs/pages/guides/gha_wheels.md, {{cookiecutter.project_name}}/.github/workflows/{% if cookiecutter.__type=='compiled' %}cd.yml{% endif %}
=> docs: rebuild wheels if gha file changes

docs/pages/guides/docs.md, {{cookiecutter.project_name}}/docs/conf.py
=> docs: link back to source

README.md, noxfile.py, src/sp_repo_review/checks/precommit.py, tests/test_precommit.py
Fix https://github.com/scientific-python/cookie/issues/459.
Move the code for multiple repos and renames into the main check function, and add tests.
=> fix: support crate-ci/typos in addition to codespell

docs/_includes/interactive_repo_review.html
=> chore: bump repo-review deps

src/sp_repo_review/checks/precommit.py, tests/test_precommit.py
=> fix: add a supported fork of the prettier mirror

.pre-commit-config.yaml, README.md, docs/pages/guides/gha_pure.md, docs/pages/guides/gha_wheels.md, docs/pages/guides/index.md, docs/pages/guides/mypy.md, docs/pages/guides/packaging_classic.md, docs/pages/guides/packaging_compiled.md, docs/pages/guides/packaging_simple.md, docs/pages/guides/style.md, docs/pages/index.md, docs/pages/principles/design.md, docs/pages/principles/index.md, docs/pages/tutorials/module.md, docs/pages/tutorials/packaging.md, docs/pages/tutorials/test.md, tests/test_precommit.py, {{cookiecutter.project_name}}/.pre-commit-config.yaml
=> fix: move the pre-commit prettier mirror

src/sp_repo_review/checks/precommit.py
The old one has some formatting issues, so let's just call it done and the new one required.
=> fix: consider the prettier mirror a rename now

.github/workflows/reusable-rr-tests.yml, noxfile.py
Working on https://github.com/scientific-python/cookie/issues/473.
=> tests: check for default encoding issues

{{cookiecutter.project_name}}/.pre-commit-config.yaml
Fix https://github.com/scikit-build/scikit-build-core/issues/866. Someone might want to remove these, but others will want to keep them (if you want to update, you need to keep them), so let's add them here so they don't fail a first-run lint.
=> fix: remove generated files from pre-commit checks

.devcontainer/devcontainer.json, action.yml, docs/_includes/pyproject.md, docs/pages/guides/packaging_classic.md, docs/pages/guides/tasks.md, docs/pages/tutorials/dev-environment.md, src/sp_repo_review/checks/readthedocs.py, {{cookiecutter.project_name}}/.pre-commit-config.yaml, {{cookiecutter.project_name}}/{% if cookiecutter.backend in ['setuptools','pybind11'] %}setup.cfg{% endif %}
3.13 is in RC. Use 3.12 in more places instead of 3.11.
=> chore: use 3.12 more places, add 3.13

docs/_includes/head_custom.html, docs/_includes/interactive_repo_review.html
Bump pyodide version, hopefully fix issue with mismatched URL type on Netlify.
=> docs: bump pyodide version

{{cookiecutter.project_name}}/.github/CONTRIBUTING.md
This adds the changes to the nox docs session arguments introduced in https://github.com/scientific-python/cookie/pull/424 to the contribution guide of the template.
=> docs: update docs session arguments in CONTRIBUTING.md

README.md, pyproject.toml, src/sp_repo_review/checks/general.py, tests/test_general.py
=> fix: add pixi support for PY007

docs/pages/guides/gha_basic.md
This is also an interesting action to list.
=> docs: setup-micromamba action mention

.github/workflows/reusable-cookie.yml, README.md, docs/_includes/pyproject.md, docs/pages/guides/gha_basic.md, docs/pages/guides/packaging_classic.md, docs/pages/guides/packaging_compiled.md, docs/pages/guides/style.md, docs/pages/guides/tasks.md, tests/packages/ruff_extend/ruff.toml, {{cookiecutter.project_name}}/.github/workflows/ci.yml, {{cookiecutter.project_name}}/pyproject.toml, {{cookiecutter.project_name}}/{% if cookiecutter.__ci=='gitlab' %}.gitlab-ci.yml{% endif %}, {{cookiecutter.project_name}}/{% if cookiecutter.backend=='maturin' %}Cargo.toml{% endif %}, {{cookiecutter.project_name}}/{% if cookiecutter.backend=='setuptools' %}setup.cfg{% endif %}
=> feat: drop Python <3.9

cookiecutter.json, copier.yml
=> fix: line spacing

docs/pages/guides/style.md, {{cookiecutter.project_name}}/pyproject.toml
=> chore: sort Ruff listings

docs/pages/guides/gha_basic.md
=> docs: move sigstore mention

docs/_includes/interactive_repo_review.html, docs/pages/guides/docs.md, noxfile.py, {{cookiecutter.project_name}}/pyproject.toml
=> feat: update Poetry to 2.0+ and PEP 621

docs/_includes/interactive_repo_review.html, docs/assets/js/webapp.js, src/sp_repo_review/checks/readthedocs.py
This includes ignore reason support.
- **fix: add tick marks around a filename**
- **docs: update webapp for repo-review 0.12.1**
=> fix: ticks and updated webapp

docs/_includes/head_custom.html, docs/_includes/interactive_repo_review.html, docs/assets/js/webapp.js
Pulling in latest repo-review.
=> chore: pull in latest repo-review

docs/pages/index.md
Adding links to a few other similar resources.
=> docs: mention other guides

src/sp_repo_review/checks/pyproject.py, tests/test_pyproject.py
Fix #575, using the new fixture from #572.
=> fix: don't error if setup.cfg missing python requires

README.md, helpers/extensions.py, noxfile.py
Work around https://github.com/copier-org/copier/issues/2113.
=> fix: copier delay computation

README.md, pyproject.toml
=> fix: better support for uvx

docs/pages/guides/gha_basic.md, docs/pages/guides/gha_pure.md, docs/pages/guides/gha_wheels.md, noxfile.py, {{cookiecutter.project_name}}/.github/workflows/{% if cookiecutter.__type!='compiled' %}cd.yml{% endif %}, {{cookiecutter.project_name}}/.github/workflows/{% if cookiecutter.__type=='compiled' %}cd.yml{% endif %}
=> fix: bump action broken due to incorrect urls

docs/pages/guides/packaging_classic.md
See https://github.com/scientific-python/learn.scientific-python.org/pull/240.
=> docs: fix link to page

README.md
Also testing #597.
----
📚 Documentation preview 📚: https://scientific-python-cookie--598.org.readthedocs.build/
=> docs: mention recent updates

docs/_includes/pyproject.md
This PR suggests some minor changes to try to improve the clarity of the depenedency-groups description.
----
📚 Documentation preview 📚: https://scientific-python-cookie--606.org.readthedocs.build/
=> Minor improvements to the depenedency-groups description

docs/pages/guides/gha_wheels.md, {{cookiecutter.project_name}}/.github/workflows/{% if cookiecutter.__type=='compiled' %}cd.yml{% endif %}
Make sure all ARM wheels are built.
----
📚 Documentation preview 📚: https://scientific-python-cookie--614.org.readthedocs.build/
=> chore: include ARM in CI

{{cookiecutter.project_name}}/.github/workflows/ci.yml
Hi there,
This change is based on this conversation: https://github.com/scikit-image/scikit-image/pull/7802#discussion_r2120147965 /cc @lagru 
Best,
Marianne
----
📚 Documentation preview 📚: https://scientific-python-cookie--609.org.readthedocs.build/
=> Fix comment about color depth.
